name: OrderIt
description: OrderIt App.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_bottom_navigation: ^0.3.2
  font_awesome_flutter: ^8.8.1
  mask_text_input_formatter: ^1.0.6 
  email_validator: ^1.0.0 
  flutter_launcher_icons: ^0.7.5
  credit_card_validate: ^0.0.3
  data_connection_checker: ^0.3.4
  cpf_cnpj_validator: ^1.0.5

  cupertino_icons: ^0.1.3
  flutter_statusbarcolor: ^0.2.3

  hive:
  path:
  path_provider: ^1.6.5
  hive_flutter:
  hive_generator:
  build_runner:
  http: ^0.12.1

  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_database:
  firebase_auth: ^0.16.0

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/orderit_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets: 
  - assets/orderit_logo.png

